Build notebook in CI workflow (#52)
* Build notebook in CI workflow

* Comment docker build to accelerate testing

* Try to get user and groud ids

* Change docker container uid and gid

* Trying ROOT instead of changing uid and gid

* Try using ROOT=TRUE and sudo

* Try again setting uid and gid after resolving miniconda conflict

* Use edge version

* Fix ls notebook

* Push HTML notebooks to GH pages with edge

* Comment out README push

* Fix typ in synapse.Rmd

* Run cached docker image

* Change tag of cached image

* Cleanup CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: CI
 
 on:
   schedule:
-    - cron: '0 10 * * *' # everyday at 10am
+    - cron: '0 10 * * 0'  # every Sunday at 10am
   push:
     branches:
       - main
@@ -13,6 +13,10 @@ on:
 
 env:
   docker_repository: tschaffter/rstudio
+  # github.event.repository.clone_url not available for on: schedule
+  clone_url: https://github.com/tschaffter/rstudio.git
+  # github.event.repository.default_branch not available for on: schedule
+  default_branch: main
 
 jobs:
   lint:
@@ -40,19 +44,20 @@ jobs:
     - name: Validate docker-compose.yml
       run: docker-compose -f docker-compose.yml config >/dev/null
 
-  docker:
+  build-and-publish:
     needs: [test]
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - name: Prepare
+
+    - name: Prepare build
       id: prep
       run: |
         DOCKER_IMAGE=${{ env.docker_repository }}
         VERSION=noop
         PUSH=false
         if [ "${{ github.event_name }}" = "schedule" ]; then
-          VERSION=nightly
+          VERSION=weekly
           PUSH=true
         elif [[ $GITHUB_REF == refs/tags/* ]]; then
           # VERSION=${GITHUB_REF#refs/tags/}
@@ -65,6 +70,7 @@ jobs:
           fi
         elif [[ $GITHUB_REF == refs/pull/* ]]; then
           VERSION=pr-${{ github.event.number }}
+          PUSH=true
         fi
         TAGS="${DOCKER_IMAGE}:${VERSION}"
         if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
@@ -82,24 +88,68 @@ jobs:
         echo ::set-output name=tags::${TAGS}
         echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
         echo ::set-output name=push::${PUSH}
+
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
+
     - name: Set up Docker Buildx
+      id: buildx
       uses: docker/setup-buildx-action@v1
-    - name: Login to DockerHub
-      if: ${{ steps.prep.outputs.push }}
+
+    - name: Cache Docker layers
+      uses: actions/cache@v2
+      with:
+        path: /tmp/.buildx-cache
+        key: ${{ runner.os }}-single-buildx-${{ github.sha }}
+        restore-keys: |
+          ${{ runner.os }}-single-buildx
+
+    - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
-    - name: Build and push
-      id: docker_build
+
+    - name: Build image
       uses: docker/build-push-action@v2
       with:
         context: .
         file: Dockerfile
+        builder: ${{ steps.buildx.outputs.name }}
+        load: true
+        push: false
         platforms: linux/amd64
-        push: ${{ steps.prep.outputs.push }}
+        tags: rstudio-cached:latest
+        cache-from: type=local,src=/tmp/.buildx-cache
+        cache-to: type=local,dest=/tmp/.buildx-cache-new
+
+    - name: Create .env
+      run: |
+        cp .env.example .env
+        printf "%s\n" \
+          "PASSWORD=${{ secrets.RSTUDIO_PASSWORD }}" \
+          "USERID=$(id -u)" \
+          "GROUPID=$(id -g)" \
+          "SYNAPSE_TOKEN=${{ secrets.SYNAPSE_TOKEN }}" | tee -a .env >/dev/null
+
+    - name: Generate HTML notebooks
+      run: |
+        docker run --rm \
+          --env-file .env \
+          -v $(pwd)/notebooks:/data \
+          rstudio-cached:latest \
+          render /data/examples/synapse.Rmd
+
+    - name: Push image
+      if: steps.prep.outputs.push == 'true'
+      id: docker_push
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: Dockerfile
+        builder: ${{ steps.buildx.outputs.name }}
+        push: true
+        platforms: linux/amd64
         tags: ${{ steps.prep.outputs.tags }}
         labels: |
           org.opencontainers.image.created=${{ steps.prep.outputs.created }}
@@ -107,10 +157,62 @@ jobs:
           org.opencontainers.image.version=${{ steps.prep.outputs.version }}
           org.opencontainers.image.revision=${{ github.sha }}
           org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
-    # - name: Docker Hub Description
+        cache-from: type=local,src=/tmp/.buildx-cache
+        cache-to: type=local,dest=/tmp/.buildx-cache-new
+
+    # - name: Update Docker Hub repository description
     #   if: steps.prep.outputs.push == 'true'
     #   uses: peter-evans/dockerhub-description@v2
     #   with:
     #     username: ${{ secrets.DOCKERHUB_USERNAME }}
     #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
     #     repository: ${{ env.docker_repository }}
+
+    - name: Prepare to publish HTML notebooks to GH Pages
+      if: steps.prep.outputs.push == 'true'
+      run: |
+        git clone ${{ env.clone_url }} \
+          --branch gh-pages --single-branch gh-pages
+
+        # Update gh-pages: version specified
+        NOTEBOOKS_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/notebooks
+        rm -fr ${NOTEBOOKS_TARGET_DIR}
+        mkdir -p ${NOTEBOOKS_TARGET_DIR}
+        cp -R notebooks/examples/*.html ${NOTEBOOKS_TARGET_DIR}
+
+        # Update gh-pages: latest, major, and minor versions
+        if [ ! -z "${{ steps.prep.outputs.version_major }}" ]; then
+          # Update latest (e.g. "1.2.3" => "latest")
+          NOTEBOOKS_TARGET_DIR=gh-pages/latest/notebooks
+          rm -fr ${NOTEBOOKS_TARGET_DIR}
+          mkdir -p ${NOTEBOOKS_TARGET_DIR}
+          cp -R notebooks/examples/*.html ${NOTEBOOKS_TARGET_DIR}
+
+          # Update major version (e.g. "1.2.3" => "1")
+          NOTEBOOKS_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}/notebooks
+          rm -fr ${NOTEBOOKS_TARGET_DIR}
+          mkdir -p ${NOTEBOOKS_TARGET_DIR}
+          cp -R notebooks/examples/*.html ${NOTEBOOKS_TARGET_DIR}
+
+          # Update minor version (e.g. "1.2.3" => "1.2")
+          NOTEBOOKS_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}/notebooks
+          rm -fr ${NOTEBOOKS_TARGET_DIR}
+          mkdir -p ${NOTEBOOKS_TARGET_DIR}
+          cp -R notebooks/examples/*.html ${NOTEBOOKS_TARGET_DIR}
+        fi
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update notebooks" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+
+    - name: Push to gh-pages
+      if: steps.prep.outputs.push == 'true'
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        force: true
